import type { LineageSubgraph, Node } from "@/lib/types";

/**
 * Code-lens generator: turns the provenance chain into a REAL, idiomatic Python
 * package — `invariant_research/` with functions grouped by stage (features.py,
 * targets.py, models.py, strategy.py), a `data.py` loader, a clean `pipeline.py`
 * that orchestrates module-qualified calls, `pyproject.toml` (pip-installable),
 * pinned `requirements.txt`, and the policies + result specs as YAML.
 *
 * HONESTY BAR (hard): code is written against the INPUT SCHEMA the user supplies
 * — never an internal storage layer, never a storage path. Operator names are the
 * real registry verbs. Same bars in → same result out.
 */

export const INPUT_SCHEMA = ["ts_event", "symbol", "open", "high", "low", "close", "volume"] as const;

/** The package every module lives under. */
export const PACKAGE = "invariant_research";

/** node.kind → module within the package (datasets load via data.py; policies are YAML). */
export const MODULE_OF_KIND: Record<string, string> = {
  feature: "features",
  matrix: "features",
  universe: "features",
  target: "targets",
  model: "models",
  strategy: "models",
  result: "strategy",
  figure: "strategy",
};

export const REQUIREMENTS = ["polars==1.12.0", "numpy==1.26.4", "scikit-learn==1.4.2", "pyarrow==15.0.0", ""].join("\n");

export const INIT_PY = `"""crude-oil-research — a reproducible quant-research pipeline (generated by Invariant)."""\n`;

export const DATA_PY = `"""Load point-in-time OHLCV bars in the canonical Invariant input schema.

Every dataset arrives as one tidy frame:
    { ts_event, symbol, open, high, low, close, volume }

Point DATA_DIR at your own databento export (or the hosted parquet) and the rest
of the pipeline reproduces deterministically — same bars in, same result out.
"""
from __future__ import annotations

from pathlib import Path

import polars as pl

SCHEMA = ["ts_event", "symbol", "open", "high", "low", "close", "volume"]
DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def load(name: str) -> pl.DataFrame:
    """Read \`<name>.parquet\`, enforce the canonical schema, sort by time."""
    df = pl.read_parquet(DATA_DIR / f"{name}.parquet")
    missing = [c for c in SCHEMA if c not in df.columns]
    if missing:
        raise ValueError(f"{name}: missing columns {missing}; expected {SCHEMA}")
    return df.select(SCHEMA).sort(["symbol", "ts_event"])
`;

export const GITIGNORE = ["__pycache__/", "*.pyc", ".venv/", "*.egg-info/", "data/*.parquet", ""].join("\n");

const sp = (n: Node): Record<string, unknown> => (n.spec ?? {}) as Record<string, unknown>;
const num = (v: unknown, d: number): number => (typeof v === "number" ? v : d);
const policyName = (n: Node): string | undefined => n.policyRefs?.[0]?.split(":")[1];
const isData = (n: Node) => n.kind === "dataset" || n.kind === "raw-dataset";

function parentsInOrder(sg: LineageSubgraph, id: string): Node[] {
  const byId = Object.fromEntries(sg.nodes.map((n) => [n.id, n]));
  return sg.edges.filter((e) => e.childId === id).map((e) => byId[e.parentId]).filter(Boolean) as Node[];
}

function depths(sg: LineageSubgraph): Record<string, number> {
  const parents: Record<string, string[]> = {};
  const isPolicy = (id: string) => sg.nodes.find((n) => n.id === id)?.kind === "policy";
  for (const n of sg.nodes) parents[n.id] = [];
  for (const e of sg.edges) if (parents[e.childId] && !isPolicy(e.parentId)) parents[e.childId].push(e.parentId);
  const d: Record<string, number> = {};
  const visit = (id: string, seen: Set<string>): number => {
    if (d[id] != null) return d[id];
    if (seen.has(id)) return 0;
    seen.add(id);
    const ps = parents[id] ?? [];
    d[id] = ps.length ? Math.max(...ps.map((p) => visit(p, seen))) + 1 : 0;
    return d[id];
  };
  for (const n of sg.nodes) visit(n.id, new Set());
  return d;
}

interface Impl { imports: string[]; def: string }

/* ── per-operator REAL implementations (type-hinted, idiomatic) ─────────────── */
function implFor(node: Node, parents: Node[], op: string): Impl {
  const out = node.name;
  const p = parents.map((x) => x.name);
  const PL = ["import polars as pl"];

  switch (op) {
    case "stitch_contracts": {
      const roll = (sp(node).roll as string) ?? "calendar";
      const adjust = (sp(node).adjust as string) ?? "panama";
      return { imports: PL, def:
`def ${out}(${p[0]}: pl.DataFrame, roll: str = "${roll}", adjust: str = "${adjust}") -> pl.DataFrame:
    """stitch_contracts — continuous front-month, ${adjust}-adjusted on the ${roll} roll.

    A roll is where the active contract (\`symbol\`) changes. The gap at each roll is
    removed by additively shifting the OLDER bars, so the continuous series has no
    artificial jump — the adjustment only ever touches PAST bars (no look-ahead).
    Governed by the \`${policyName(node) ?? "roll_stitch"}\` policy.
    """
    df = ${p[0]}.sort("ts_event")
    is_roll = (pl.col("symbol") != pl.col("symbol").shift(1)).fill_null(False)
    gap = pl.when(is_roll).then(pl.col("close") - pl.col("close").shift(1)).otherwise(0.0)
    adj = gap.sum() - gap.cum_sum()
    return df.with_columns([(pl.col(c) + adj).alias(c) for c in ("open", "high", "low", "close")])` };
    }
    case "derive_column":
      return { imports: PL, def:
`def ${out}(${p[0]}: pl.DataFrame) -> pl.DataFrame:
    """derive_column — one-bar log return of the continuous close.

    log(close) - log(close.shift(1)); the first bar is null (no prior price) and is
    never back-filled.
    """
    log_ret = (pl.col("close").log() - pl.col("close").shift(1).log()).alias("${out}")
    return ${p[0]}.sort("ts_event").select([pl.col("ts_event"), log_ret])` };
    case "rolling_zscore": {
      const w = num(sp(node).window, 20);
      if (parents[0] && isData(parents[0]))
        return { imports: PL, def:
`def ${out}(${p[0]}: pl.DataFrame, window: int = ${w}) -> pl.DataFrame:
    """rolling_zscore — trailing z-score of log returns over \`window\` bars.

    The window ENDS at t and needs \`window\` observations (min_periods=window), so
    the first window-1 rows are null — strictly causal. This is what makes the
    \`no-lookahead\` law provable, not merely asserted.
    """
    df = ${p[0]}.sort("ts_event").with_columns(
        (pl.col("close").log() - pl.col("close").shift(1).log()).alias("_ret")
    )
    r = pl.col("_ret")
    mean = r.rolling_mean(window, min_periods=window)
    std = r.rolling_std(window, min_periods=window)
    return df.select([pl.col("ts_event"), ((r - mean) / std).alias("${out}")])` };
      return { imports: PL, def:
`def ${out}(${p[0]}: pl.DataFrame, window: int = ${w}) -> pl.DataFrame:
    """rolling_zscore — trailing z-score of \`${p[0]}\` over \`window\` bars.

    The window ENDS at t and needs \`window\` observations (min_periods=window), so
    the first window-1 rows are null — strictly causal (no look-ahead).
    """
    x = pl.col("${p[0]}")
    mean = x.rolling_mean(window, min_periods=window)
    std = x.rolling_std(window, min_periods=window)
    return ${p[0]}.sort("ts_event").select([pl.col("ts_event"), ((x - mean) / std).alias("${out}")])` };
    }
    case "coint_spread": {
      const lb = num(sp(node).lookback, 60);
      return { imports: PL, def:
`def ${out}(${p[0]}: pl.DataFrame, ${p[1]}: pl.DataFrame, lookback: int = ${lb}) -> pl.DataFrame:
    """coint_spread — standardised cointegration residual of two log-price series.

    Rolling hedge ratio beta = cov(a, b) / var(b) on log prices over \`lookback\`
    bars; spread = log(a) - beta*log(b); then z-scored over the same trailing
    window. Every window is trailing — no look-ahead.
    """
    a = ${p[0]}.select([pl.col("ts_event"), pl.col("close").log().alias("a")]).sort("ts_event")
    b = ${p[1]}.select([pl.col("ts_event"), pl.col("close").log().alias("b")]).sort("ts_event")
    j = a.join(b, on="ts_event", how="inner")
    ca, cb = pl.col("a"), pl.col("b")
    cov = (ca * cb).rolling_mean(lookback) - ca.rolling_mean(lookback) * cb.rolling_mean(lookback)
    var = (cb * cb).rolling_mean(lookback) - cb.rolling_mean(lookback) ** 2
    j = j.with_columns((cov / var).alias("beta"))
    j = j.with_columns((ca - pl.col("beta") * cb).alias("spread"))
    s = pl.col("spread")
    mean = s.rolling_mean(lookback, min_periods=lookback)
    std = s.rolling_std(lookback, min_periods=lookback)
    return j.select([pl.col("ts_event"), ((s - mean) / std).alias("${out}")])` };
    }
    case "join_feature": {
      const cols = (sp(node).columns as string[]) ?? p;
      const sig = p.map((v) => `${v}: pl.DataFrame`).join(", ");
      const others = p.slice(1).map((v) => `${v}.sort("ts_event")`).join(", ");
      return { imports: PL, def:
`def ${out}(${sig}) -> pl.DataFrame:
    """join_feature — as-of align the signals onto one time index.

    join_asof carries each signal's last known value forward to the base clock, so
    nothing from the future leaks across instruments. Columns: ${cols.join(", ")}.
    """
    m = ${p[0]}.sort("ts_event")
    for f in (${others}):
        m = m.join_asof(f, on="ts_event")
    return m.drop_nulls()` };
    }
    case "lead": {
      const periods = num(sp(node).periods, 5);
      const unit = (sp(node).unit as string) ?? "";
      const srcCol = parents[0] ? parents[0].name : "close";
      return { imports: PL, def:
`def ${out}(${p[0]}: pl.DataFrame, periods: int = ${periods}) -> pl.DataFrame:
    """lead — the TARGET: the return realised over the NEXT \`periods\` bars${unit ? ` (${unit})` : ""}.

    shift(-periods) looks FORWARD on purpose — it is the label we predict, never fed
    back in as a feature, so it cannot leak into training.
    """
    return ${p[0]}.sort("ts_event").select(
        [pl.col("ts_event"), pl.col("${srcCol}").shift(-periods).alias("${out}")]
    )` };
    }
    case "fit_model": {
      const alpha = num(sp(node).alpha, 0.1);
      const matrix = parents.find((x) => x.kind === "matrix") ?? parents[0];
      const target = parents.find((x) => x.kind === "target") ?? parents[1];
      const feats = (sp(matrix).columns as string[]) ?? ["zscore_20", "gas_z20", "spread_5d"];
      const featList = feats.map((c) => `"${c}"`).join(", ");
      return { imports: ["import polars as pl", "from sklearn.linear_model import Ridge"], def:
`def ${out}(${matrix.name}: pl.DataFrame, ${target.name}: pl.DataFrame, alpha: float = ${alpha}) -> dict:
    """fit_model — ridge regression of the forward return on the signals.

    Fit on the aligned, non-null rows only. Returns the fitted estimator plus the
    feature order, so scoring downstream is reproducible.
    """
    df = ${matrix.name}.join(${target.name}, on="ts_event", how="inner").drop_nulls()
    features = [${featList}]
    X = df.select(features).to_numpy()
    y = df["${target.name}"].to_numpy()
    estimator = Ridge(alpha=alpha).fit(X, y)
    return {"estimator": estimator, "features": features}` };
    }
    case "evaluate_strategy": {
      const window = ((sp(node).evalWindow as string) ?? "2024-01-02 .. 2024-06-28").split("..").map((s) => s.trim());
      const pol = sp(node).policy as string;
      return { imports: ["import numpy as np", "import polars as pl"], def:
`def ${out}(model: dict, matrix: pl.DataFrame, target: pl.DataFrame, window: tuple[str, str] = ("${window[0]}", "${window[1]}")) -> dict:
    """evaluate_strategy — top/bottom-decile dollar-neutral backtest.

    Policy \`${pol ?? "position_sizing"}\`: +1 the top signal decile, -1 the bottom,
    demeaned to dollar-neutral. PnL = position * realised forward return; Sharpe
    annualised from 1-minute bars.
    """
    df = matrix.join(target, on="ts_event", how="inner").drop_nulls()
    lo, hi = window
    df = df.filter(
        (pl.col("ts_event") >= pl.lit(lo).str.to_datetime())
        & (pl.col("ts_event") <= pl.lit(hi).str.to_datetime())
    )
    X = df.select(model["features"]).to_numpy()
    signal = model["estimator"].predict(X)
    hi_d, lo_d = np.quantile(signal, 0.9), np.quantile(signal, 0.1)
    pos = np.where(signal >= hi_d, 1.0, np.where(signal <= lo_d, -1.0, 0.0))
    pos = pos - pos.mean()  # dollar-neutral
    target_col = [c for c in target.columns if c != "ts_event"][0]
    ret = df[target_col].to_numpy()
    pnl = pos * ret
    sharpe = float(pnl.mean() / pnl.std() * np.sqrt(252 * 390)) if pnl.std() else 0.0
    traded = pos != 0
    hit = float((np.sign(pos)[traded] == np.sign(ret)[traded]).mean()) if traded.any() else 0.0
    curve = np.cumsum(pnl)
    max_dd = float((curve - np.maximum.accumulate(curve)).min())
    return {
        "sharpe": round(sharpe, 2),
        "hit_rate": round(hit, 3),
        "max_drawdown": round(max_dd, 3),
        "turnover": round(float(np.abs(np.diff(pos)).mean()), 2),
    }` };
    }
    default:
      return { imports: PL, def:
`def ${out}(${p.join(", ") || "df"}):
    """${op || "operator"} — produces \`${out}\`. (Implementation pending.)"""
    raise NotImplementedError("${op || out}")` };
  }
}

const moduleOf = (n: Node): string => MODULE_OF_KIND[n.kind] ?? "features";
const opOf = (n: Node, producerOps: Record<string, string>): string =>
  producerOps[n.id] ?? (sp(n).operator as string) ?? "";

/** One artifact's function source, with a small header (for the inspector Code tab). */
export function buildCodeMap(sg: LineageSubgraph, producerOps: Record<string, string>): Record<string, string> {
  const map: Record<string, string> = {};
  for (const n of sg.nodes) {
    if (n.kind === "policy" || isData(n)) continue;
    const op = opOf(n, producerOps);
    const impl = implFor(n, parentsInOrder(sg, n.id), op);
    map[n.id] = [`# ${PACKAGE}/${moduleOf(n)}.py · ${n.name}`, "", ...impl.imports, "", impl.def, ""].join("\n");
  }
  return map;
}

/** A whole module file: the functions of every artifact that lives in it. */
export function buildModule(moduleName: string, sg: LineageSubgraph, producerOps: Record<string, string>): string {
  const d = depths(sg);
  const nodes = sg.nodes
    .filter((n) => !isData(n) && n.kind !== "policy" && moduleOf(n) === moduleName)
    .sort((a, b) => (d[a.id] ?? 0) - (d[b.id] ?? 0));
  const impls = nodes.map((n) => implFor(n, parentsInOrder(sg, n.id), opOf(n, producerOps)));
  const imports = Array.from(new Set(impls.flatMap((i) => i.imports)));
  return ["from __future__ import annotations", "", ...imports, "", "", impls.map((i) => i.def).join("\n\n\n"), ""].join("\n");
}

/** Which module files this graph needs (in stage order). */
export function moduleNames(sg: LineageSubgraph): string[] {
  const order = ["features", "targets", "models", "strategy"];
  const present = new Set(sg.nodes.filter((n) => !isData(n) && n.kind !== "policy").map((n) => moduleOf(n)));
  return order.filter((m) => present.has(m));
}

/** pipeline.py — module-qualified, no name shadowing, idiomatic. */
export function buildPipeline(sg: LineageSubgraph, producerOps: Record<string, string>, projectName = "pipeline"): string {
  const d = depths(sg);
  const flow = sg.nodes.filter((n) => n.kind !== "policy").sort((a, b) => (d[a.id] ?? 0) - (d[b.id] ?? 0));
  const mods = moduleNames(sg);
  const body: string[] = [];
  for (const n of flow) {
    if (isData(n)) { body.push(`    ${n.name} = data.load("${n.name}")`); continue; }
    const op = opOf(n, producerOps);
    const mod = moduleOf(n);
    const parents = parentsInOrder(sg, n.id);
    if (op === "evaluate_strategy") {
      const model = parents.find((x) => x.kind === "model") ?? parents[0];
      const train = model ? parentsInOrder(sg, model.id) : [];
      const matrix = train.find((x) => x.kind === "matrix");
      const target = train.find((x) => x.kind === "target");
      const args = [model?.name, matrix?.name, target?.name].filter(Boolean).join(", ");
      body.push(`    ${n.name} = ${mod}.${n.name}(${args})`);
    } else {
      body.push(`    ${n.name} = ${mod}.${n.name}(${parents.map((p) => p.name).join(", ")})`);
    }
  }
  const terminal = [...flow].reverse().find((n) => n.kind === "result") ?? flow[flow.length - 1];
  const imports = ["data", ...mods].join(", ");
  return [
    `"""${projectName} — reproducible pipeline (generated by Invariant).`,
    ``,
    `Same bars in -> same result out:`,
    `    pip install -e .`,
    `    python -m ${PACKAGE}.pipeline`,
    `"""`,
    `from __future__ import annotations`,
    ``,
    `from ${PACKAGE} import ${imports}`,
    ``,
    ``,
    `def build() -> dict:`,
    ...(body.length ? body : ["    return {}  # build something first"]),
    `    return ${terminal?.name ?? "{}"}`,
    ``,
    ``,
    `if __name__ == "__main__":`,
    `    print(build())`,
    ``,
  ].join("\n");
}

/** A readable composition line for an edge/child: `child = module.child(parents, params)`. */
function opParams(child: Node, op: string): string[] {
  const s = sp(child);
  if (op === "rolling_zscore") return [`window=${num(s.window, 20)}`];
  if (op === "coint_spread") return [`lookback=${num(s.lookback, 60)}`];
  if (op === "lead") return [`periods=${num(s.periods, 5)}`];
  if (op === "fit_model") return [`alpha=${num(s.alpha, 0.1)}`];
  if (op === "evaluate_strategy" && s.policy) return [`policy="${s.policy}"`];
  if (op === "stitch_contracts") return [s.roll ? `roll="${s.roll}"` : "", s.adjust ? `adjust="${s.adjust}"` : ""].filter(Boolean);
  return [];
}
export function callLine(child: Node, parents: Node[], op: string): string {
  const mod = MODULE_OF_KIND[child.kind] ?? "features";
  const args = [...parents.map((p) => p.name), ...opParams(child, op)].join(", ");
  return `${child.name} = ${mod}.${child.name}(${args})`;
}
export function opLabel(child: Node, op: string): string {
  const p = opParams(child, op);
  return p.length ? `${op} · ${p[0].replace(/^(\w+)=/, "")}` : op;
}

export function datasetCode(id: string): string {
  return [`# load point-in-time bars in the canonical schema:`, `#   { ${INPUT_SCHEMA.join(", ")} }`, `from ${PACKAGE}.data import load`, ``, `df = load("${id}")`, `df.head()`].join("\n");
}

export function buildPyproject(projectName: string): string {
  const slug = projectName.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  return [
    `[project]`,
    `name = "${slug}"`,
    `version = "0.1.0"`,
    `requires-python = ">=3.11"`,
    `dependencies = ["polars>=1.12", "numpy>=1.26", "scikit-learn>=1.4", "pyarrow>=15"]`,
    ``,
    `[build-system]`,
    `requires = ["setuptools>=68"]`,
    `build-backend = "setuptools.build_meta"`,
    ``,
    `[tool.setuptools]`,
    `packages = ["${PACKAGE}"]`,
    ``,
  ].join("\n");
}

export function buildReadme(projectName: string, sg: LineageSubgraph): string {
  const result = [...sg.nodes].reverse().find((n) => n.kind === "result");
  const datasets = sg.nodes.filter(isData).map((n) => `\`${n.name}\``).join(", ");
  return [
    `# ${projectName}`,
    ``,
    `A reproducible quantitative-research pipeline generated by **Invariant**. Each`,
    `stage is a function in the \`${PACKAGE}\` package; \`${PACKAGE}/pipeline.py\` runs`,
    `the whole DAG end-to-end. Same bars in → same result out.`,
    ``,
    `## Run it yourself`,
    ``,
    "```bash",
    `pip install -e .`,
    `# drop your point-in-time bars in data/ as <name>.parquet:`,
    `#   { ${INPUT_SCHEMA.join(", ")} }`,
    `python -m ${PACKAGE}.pipeline`,
    "```",
    ``,
    `## Inputs`,
    ``,
    `${datasets || "—"} — point-in-time OHLCV, 1-minute bars.`,
    ``,
    result ? `## Result\n\n\`${result.name}\` — ${(sp(result).evalWindow as string) ?? "see specs/"}.` : "",
    ``,
    `## Laws this pipeline holds`,
    ``,
    `- **no-lookahead** — every rolling window ends at \`t\`; the target leads forward and is never a feature.`,
    `- **reproducible** — pinned dependencies + deterministic ops ⇒ identical output on the same data.`,
    ``,
  ].join("\n");
}

export function buildConfigYaml(sg: LineageSubgraph): string {
  const datasets = sg.nodes.filter(isData).map((n) => `  - ${n.name}`);
  const result = [...sg.nodes].reverse().find((n) => n.kind === "result");
  const win = result ? ((sp(result).evalWindow as string) ?? "") : "";
  return [`# run configuration`, `data_sources:`, ...(datasets.length ? datasets : ["  - —"]), win ? `eval_window: "${win}"` : "", `random_seed: 7`, ``].filter(Boolean).join("\n");
}

export function buildSpecYaml(node: Node): string {
  const s = sp(node);
  return [
    `# spec: ${node.name}`,
    `kind: ${node.kind}`,
    node.version ? `version: ${node.version}` : null,
    s.operator ? `operator: ${s.operator}` : null,
    s.evalWindow ? `eval_window: "${s.evalWindow}"` : null,
    s.policy ? `policy: ${s.policy}` : null,
    node.lineageHash ? `lineage_hash: ${node.lineageHash}` : null,
    node.contentHash ? `content_hash: ${node.contentHash}` : null,
    node.asOfKnowledgeTime ? `as_of_knowledge_time: ${node.asOfKnowledgeTime}` : null,
    `reproducible: true`,
    ``,
  ].filter(Boolean).join("\n");
}
